# Shadowrocket: 2026-04-25
[General]
ipv6 = false
bypass-system = true
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local
bypass-tun = 10.0.0.0/8,127.0.0.0/8,172.16.0.0/12,192.168.0.0/16,224.0.0.0/4,255.255.255.255/32
dns-server = https://1.1.1.1/dns-query,https://dns.google/dns-query
fallback-dns = https://dns.alidns.com/dns-query,https://doh.pub/dns-query
dns-fallback-filter = geoip-cn
update-url = https://raw.githubusercontent.com/lgup/rocket/master/TvOS.conf

[Rule]
## === Apple / tvOS ===
DOMAIN-SUFFIX,apple.com,DIRECT
DOMAIN-SUFFIX,icloud.com,DIRECT
DOMAIN-SUFFIX,mzstatic.com,DIRECT
DOMAIN-SUFFIX,cdn-apple.com,DIRECT
DOMAIN-SUFFIX,aaplimg.com,DIRECT
DOMAIN-SUFFIX,apple-cloudkit.com,DIRECT
DOMAIN-SUFFIX,appstore.com,DIRECT

## Emby(直连）
DOMAIN-SUFFIX,zhezhi.art,DIRECT

## Emby(代理）
DOMAIN-SUFFIX,cn2gias.uk,PROXY
DOMAIN-SUFFIX,emby.wtf,PROXY
DOMAIN-SUFFIX,jmsuper.com,PROXY
DOMAIN-SUFFIX,lilyemby.com,PROXY
DOMAIN-SUFFIX,kws.moe,PROXY
DOMAIN-SUFFIX,echoflix.de,PROXY
DOMAIN-SUFFIX,embymv.link,PROXY
DOMAIN-SUFFIX,uhdnow.com,PROXY

## YouTube / coupang 视频
DOMAIN-SUFFIX,youtube.com,PROXY
DOMAIN-SUFFIX,youtube-nocookie.com,PROXY
DOMAIN-SUFFIX,youtu.be,PROXY
DOMAIN-SUFFIX,googlevideo.com,PROXY
DOMAIN-SUFFIX,ytimg.com,PROXY
DOMAIN-SUFFIX,ggpht.com,PROXY
DOMAIN-SUFFIX,google.com,PROXY
DOMAIN-SUFFIX,googleapis.com,PROXY
DOMAIN-SUFFIX,googleusercontent.com,PROXY
DOMAIN-SUFFIX,googletagmanager.com,PROXY
DOMAIN-SUFFIX,gstatic.com,PROXY
DOMAIN-SUFFIX,coupangplay.com,PROXY
DOMAIN-SUFFIX,coupangcdn.com,PROXY

## === 其他 ===
GEOIP,CN,DIRECT
FINAL,PROXY
